### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by dhasial** [bakfile/bak-python#55]
I just wanted to say, thank you for making this - I love it!
It's so cool having a proper manager for bakfiles, as early in development as it may be. So glad this exists.

(This is not an issue so it can be deleted to prevent clutter. I just wanted to show my appreciation.)

**Comment by ChanceNCounter** [comment]
Thank you! There's a big update coming that much improves the bak listing, adds the beginnings of command-line config access, and colorizes most of the app, because it's tough to read once there are a bunch of bakfiles.

The holdup on that is figuring out the best config layout for "fast mode" when people want it (more or less) the way it is right now, for Unixy quickness.

**Comment by dhasial** [comment]
That all sounds like some great additions. Colorized terminal text is always welcomed even just for the aesthetic, and wanting to keep it quick is a great goal, that kind of snappiness is part of why I go for ncurses-type frontends over GUIs every time.
